development:
  adapter: postgresql
  encoding: unicode
  database: rail_youtube_friday_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: rail_youtube_friday_test
  pool: 5

